In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split


from sklearn.datasets import load_breast_cancer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


from sklearn.metrics import accuracy_score,precision_score,recall_score

from sklearn.metrics import confusion_matrix,classification_report

from sklearn.model_selection import GridSearchCV

#. Decision Tree: Overfitting vs Underfitting

In [4]:
# Load the dataset.
df = pd.read_csv('/content/Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Q = Split it into 80% training and 20% testing data.
X = df.drop(['Species'],axis = 1,errors='ignore')
y = df['Species']
X_train , X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [6]:
# Model A: max_depth=2
model_A = DecisionTreeClassifier(max_depth=2, random_state=42)
model_A.fit(X_train, y_train)

y_pred_train_A = model_A.predict(X_train)
y_pred_test_A = model_A.predict(X_test)
print(f"Model A - Training Accuracy : {accuracy_score(y_train, y_pred_train_A):.4f}")
print(f"Model A - Testing Accuracy : {accuracy_score(y_test, y_pred_test_A):.4f}")

Model A - Training Accuracy : 1.0000
Model A - Testing Accuracy : 1.0000

In [7]:
# Train two Decision Tree models: Model A: max_depth=None
model_B = DecisionTreeClassifier(max_depth=None)
model_B.fit(X_train, y_train)

# Training Accuracy
y_pred_train_MA = model_A.predict(X_train)
print(f"Training Accuracy : {accuracy_score(y_train, y_pred_train_MA):.4f}")

# Testing
y_pred_test_MA = model_B.predict(X_test)
print(f"Testing Accuracy : {accuracy_score(y_test, y_pred_test_MA):.4f}")

Training Accuracy : 1.0000
Testing Accuracy : 1.0000

#2. Finding the Best Tree Depth

In [8]:
df = pd.read_csv('/content/winequality-red.csv')
df.sample(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1542,6.7,0.855,0.02,1.9,0.064,29.0,38.0,0.99472,3.30,0.56,10.75,6
695,5.1,0.470,0.02,1.3,0.034,18.0,44.0,0.99210,3.90,0.62,12.80,6
318,9.8,0.660,0.39,3.2,0.083,21.0,59.0,0.99890,3.37,0.71,11.50,7
133,6.6,0.500,0.01,1.5,0.060,17.0,26.0,0.99520,3.40,0.58,9.80,6
280,11.4,0.260,0.44,3.6,0.071,6.0,19.0,0.99860,3.12,0.82,9.30,6

In [9]:
df.shape

(1599, 12)

In [10]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [14]:
df.columns.to_list()

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [27]:
X = df.drop(['quality'], axis = 1)
y = df['quality']
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [30]:
model_2 = DecisionTreeClassifier(max_depth=2, random_state=42)
model_2.fit(X_train, y_train)
train_acc_2 = accuracy_score(y_train, model_2.predict(X_train))
test_acc_2 = accuracy_score(y_test, model_2.predict(X_test))

In [31]:
model_4 = DecisionTreeClassifier(max_depth=4, random_state=42)
model_4.fit(X_train, y_train)
train_acc_4 = accuracy_score(y_train, model_4.predict(X_train))
test_acc_4 = accuracy_score(y_test, model_4.predict(X_test))

In [32]:
# --- Model 3: depth = 6 ---
model_6 = DecisionTreeClassifier(max_depth=6, random_state=42)
model_6.fit(X_train, y_train)
train_acc_6 = accuracy_score(y_train, model_6.predict(X_train))
test_acc_6 = accuracy_score(y_test, model_6.predict(X_test))

In [33]:
# --- Model 4: depth = 8 ---
model_8 = DecisionTreeClassifier(max_depth=8, random_state=42)
model_8.fit(X_train, y_train)
train_acc_8 = accuracy_score(y_train, model_8.predict(X_train))
test_acc_8 = accuracy_score(y_test, model_8.predict(X_test))

In [34]:
# --- Model 5: depth = None ---
model_none = DecisionTreeClassifier(max_depth=None, random_state=42)
model_none.fit(X_train, y_train)
train_acc_none = accuracy_score(y_train, model_none.predict(X_train))
test_acc_none = accuracy_score(y_test, model_none.predict(X_test))

In [35]:
data = {
    'max_depth': [2, 4, 6, 8, 'None'],
    'Train Accuracy': [train_acc_2, train_acc_4, train_acc_6, train_acc_8, train_acc_none],
    'Test Accuracy': [test_acc_2, test_acc_4, test_acc_6, test_acc_8, test_acc_none]
}

table = pd.DataFrame(data)
print(table)

  max_depth  Train Accuracy  Test Accuracy
0         2        0.569977        0.51250
1         4        0.630180        0.56250
2         6        0.712275        0.57500
3         8        0.802189        0.58125
4      None        1.000000        0.60625